"""add reading_state created_at and relationships

Revision ID: 780a01d9a7ee
Revises: ba7c5b9dbcad
Create Date: 2026-04-11 10:06:19.754851
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '780a01d9a7ee'
down_revision: Union[str, None] = 'ba7c5b9dbcad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading_state', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading_state', 'created_at')
    # ### end Alembic commands ###
