"""initial_schema

Revision ID: 8b38146465ab
Revises: 
Create Date: 2026-04-02 13:49:47.686419
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

revision: str = '8b38146465ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.Enum('SECTION_CONTENT', 'SECTION_SUMMARY', 'BOOK_SUMMARY', name='contenttype'), nullable=False),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('text_start', sa.Integer(), nullable=True),
    sa.Column('text_end', sa.Integer(), nullable=True),
    sa.Column('selected_text', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('HIGHLIGHT', 'NOTE', 'FREEFORM', name='annotationtype'), nullable=False),
    sa.Column('linked_annotation_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['linked_annotation_id'], ['annotations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_annotations_content', 'annotations', ['content_type', 'content_id'], unique=False)
    op.create_table('authors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_format', sa.String(length=10), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('cover_image', sa.LargeBinary(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADING', 'PARSING', 'PARSED', 'SUMMARIZING', 'COMPLETED', 'PARSE_FAILED', name='bookstatus'), nullable=False),
    sa.Column('quick_summary', sa.Text(), nullable=True),
    sa.Column('overall_summary', sa.Text(), nullable=True),
    sa.Column('overall_summary_eval', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_index('ix_books_file_hash', 'books', ['file_hash'], unique=False)
    op.create_index('ix_books_status', 'books', ['status'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('book_authors',
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'author_id')
    )
    op.create_table('book_sections',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=True),
    sa.Column('content_token_count', sa.Integer(), nullable=True),
    sa.Column('summary_md', sa.Text(), nullable=True),
    sa.Column('summary_status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'STALE', name='summarystatus'), nullable=False),
    sa.Column('summary_version', sa.String(length=50), nullable=True),
    sa.Column('summary_eval', sa.JSON(), nullable=True),
    sa.Column('summary_model', sa.String(length=100), nullable=True),
    sa.Column('user_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['book_sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_book_sections_book_id_order', 'book_sections', ['book_id', 'order_index'], unique=False)
    op.create_index('ix_book_sections_summary_status', 'book_sections', ['summary_status'], unique=False)
    op.create_table('external_references',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('quality_notes', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_external_references_book_id', 'external_references', ['book_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('step', sa.Enum('PARSE', 'SUMMARIZE', 'EMBED', 'EVAL', 'CAPTION', 'QUICK_SUMMARY', 'EXTERNAL_REFS', name='processingstep'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='processingjobstatus'), nullable=False),
    sa.Column('progress', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_processing_jobs_book_status', 'processing_jobs', ['book_id', 'status'], unique=False)
    op.create_table('search_index',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_type', sa.Enum('BOOK_TITLE', 'BOOK_SUMMARY', 'SECTION_TITLE', 'SECTION_CONTENT', 'SECTION_SUMMARY', 'CONCEPT', 'ANNOTATION', name='sourcetype'), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('embedding', Vector(dim=768), nullable=True),
    sa.Column('tsvector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_index_book_id', 'search_index', ['book_id'], unique=False)
    op.create_index('ix_search_index_embedding', 'search_index', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_search_index_source', 'search_index', ['source_type', 'source_id'], unique=False)
    op.create_index('ix_search_index_tsvector', 'search_index', ['tsvector'], unique=False, postgresql_using='gin')
    op.create_table('taggables',
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('taggable_type', sa.String(length=50), nullable=False),
    sa.Column('taggable_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'taggable_type', 'taggable_id')
    )
    op.create_table('concepts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('first_section_id', sa.BigInteger(), nullable=True),
    sa.Column('term', sa.String(length=500), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('related_concepts', sa.JSON(), nullable=True),
    sa.Column('user_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['first_section_id'], ['book_sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'term', name='uq_concepts_book_term')
    )
    op.create_index('ix_concepts_book_id', 'concepts', ['book_id'], unique=False)
    op.create_table('eval_traces',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('section_id', sa.BigInteger(), nullable=False),
    sa.Column('assertion_name', sa.String(length=100), nullable=False),
    sa.Column('assertion_category', sa.String(length=50), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('prompt_sent', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('llm_response', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['book_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_eval_traces_assertion', 'eval_traces', ['assertion_name', 'passed'], unique=False)
    op.create_index('ix_eval_traces_section', 'eval_traces', ['section_id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('section_id', sa.BigInteger(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('caption_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['book_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concept_sections',
    sa.Column('concept_id', sa.BigInteger(), nullable=False),
    sa.Column('section_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['book_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('concept_id', 'section_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concept_sections')
    op.drop_table('images')
    op.drop_index('ix_eval_traces_section', table_name='eval_traces')
    op.drop_index('ix_eval_traces_assertion', table_name='eval_traces')
    op.drop_table('eval_traces')
    op.drop_index('ix_concepts_book_id', table_name='concepts')
    op.drop_table('concepts')
    op.drop_table('taggables')
    op.drop_index('ix_search_index_tsvector', table_name='search_index', postgresql_using='gin')
    op.drop_index('ix_search_index_source', table_name='search_index')
    op.drop_index('ix_search_index_embedding', table_name='search_index', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_search_index_book_id', table_name='search_index')
    op.drop_table('search_index')
    op.drop_index('ix_processing_jobs_book_status', table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index('ix_external_references_book_id', table_name='external_references')
    op.drop_table('external_references')
    op.drop_index('ix_book_sections_summary_status', table_name='book_sections')
    op.drop_index('ix_book_sections_book_id_order', table_name='book_sections')
    op.drop_table('book_sections')
    op.drop_table('book_authors')
    op.drop_table('tags')
    op.drop_index('ix_books_status', table_name='books')
    op.drop_index('ix_books_file_hash', table_name='books')
    op.drop_table('books')
    op.drop_table('authors')
    op.drop_index('ix_annotations_content', table_name='annotations')
    op.drop_table('annotations')
    # ### end Alembic commands ###
