"""add web interface tables

Revision ID: ba7c5b9dbcad
Revises: 48151a25cc0d
Create Date: 2026-04-10 21:24:39.457395
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ba7c5b9dbcad'
down_revision: Union[str, None] = '48151a25cc0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_views',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('display_mode', sa.String(length=20), server_default='grid', nullable=False),
    sa.Column('sort_field', sa.String(length=50), server_default='updated_at', nullable=False),
    sa.Column('sort_direction', sa.String(length=4), server_default='desc', nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('table_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_presets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('font_family', sa.String(length=100), server_default='Georgia', nullable=False),
    sa.Column('font_size_px', sa.Integer(), server_default='16', nullable=False),
    sa.Column('line_spacing', sa.Float(), server_default='1.6', nullable=False),
    sa.Column('content_width_px', sa.Integer(), server_default='720', nullable=False),
    sa.Column('theme', sa.String(length=50), server_default='light', nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recent_searches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('query', sa.String(length=1000), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_threads',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['ai_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_state',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=True),
    sa.Column('section_id', sa.BigInteger(), nullable=True),
    sa.Column('scroll_position', sa.Float(), nullable=True),
    sa.Column('content_mode', sa.String(length=20), server_default='summary', nullable=False),
    sa.Column('reading_preset_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reading_preset_id'], ['reading_presets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['book_sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_agent')
    )
    # ### end Alembic commands ###

    # Seed data: 4 system reading presets
    reading_presets = sa.table(
        "reading_presets",
        sa.column("name", sa.String),
        sa.column("font_family", sa.String),
        sa.column("font_size_px", sa.Integer),
        sa.column("line_spacing", sa.Float),
        sa.column("content_width_px", sa.Integer),
        sa.column("theme", sa.String),
        sa.column("is_system", sa.Boolean),
    )
    op.bulk_insert(reading_presets, [
        {
            "name": "Comfortable",
            "font_family": "Georgia",
            "font_size_px": 18,
            "line_spacing": 1.8,
            "content_width_px": 680,
            "theme": "light",
            "is_system": True,
        },
        {
            "name": "Night Reading",
            "font_family": "Georgia",
            "font_size_px": 17,
            "line_spacing": 1.7,
            "content_width_px": 700,
            "theme": "dark",
            "is_system": True,
        },
        {
            "name": "Study Mode",
            "font_family": "Inter",
            "font_size_px": 15,
            "line_spacing": 1.5,
            "content_width_px": 800,
            "theme": "light",
            "is_system": True,
        },
        {
            "name": "Compact",
            "font_family": "Inter",
            "font_size_px": 14,
            "line_spacing": 1.4,
            "content_width_px": 900,
            "theme": "light",
            "is_system": True,
        },
    ])

    # Seed data: 1 default library view
    library_views = sa.table(
        "library_views",
        sa.column("name", sa.String),
        sa.column("display_mode", sa.String),
        sa.column("sort_field", sa.String),
        sa.column("sort_direction", sa.String),
        sa.column("position", sa.Integer),
        sa.column("is_default", sa.Boolean),
    )
    op.bulk_insert(library_views, [
        {
            "name": "All Books",
            "display_mode": "grid",
            "sort_field": "updated_at",
            "sort_direction": "desc",
            "position": 0,
            "is_default": True,
        },
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading_state')
    op.drop_table('ai_messages')
    op.drop_table('ai_threads')
    op.drop_table('recent_searches')
    op.drop_table('reading_presets')
    op.drop_table('library_views')
    # ### end Alembic commands ###
