"""add_image_relevance_alttext_hash

Revision ID: bb35febd1383
Revises: a1b2c3d4e5f6
Create Date: 2026-04-02 19:02:26.333460
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bb35febd1383'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('relevance', sa.String(length=20), nullable=True))
    op.add_column('images', sa.Column('alt_text', sa.Text(), nullable=True))
    op.add_column('images', sa.Column('content_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'content_hash')
    op.drop_column('images', 'alt_text')
    op.drop_column('images', 'relevance')
    # ### end Alembic commands ###
