"""initial sqlite schema

Revision ID: e152941ea209
Revises: 
Create Date: 2026-04-12 08:02:43.275862
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'e152941ea209'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum('SECTION_CONTENT', 'SECTION_SUMMARY', 'BOOK_SUMMARY', name='contenttype'), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('text_start', sa.Integer(), nullable=True),
    sa.Column('text_end', sa.Integer(), nullable=True),
    sa.Column('selected_text', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('HIGHLIGHT', 'NOTE', 'FREEFORM', name='annotationtype'), nullable=False),
    sa.Column('linked_annotation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['linked_annotation_id'], ['annotations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.create_index('ix_annotations_content', ['content_type', 'content_id'], unique=False)

    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_format', sa.String(length=10), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('cover_image', sa.LargeBinary(), nullable=True),
    sa.Column('default_summary_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADING', 'PARSING', 'PARSED', 'SUMMARIZING', 'COMPLETED', 'PARSE_FAILED', name='bookstatus'), nullable=False),
    sa.Column('quick_summary', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['default_summary_id'], ['summaries.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index('ix_books_file_hash', ['file_hash'], unique=False)
        batch_op.create_index('ix_books_status', ['status'], unique=False)

    op.create_table('library_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('display_mode', sa.String(length=20), server_default='grid', nullable=False),
    sa.Column('sort_field', sa.String(length=50), server_default='updated_at', nullable=False),
    sa.Column('sort_direction', sa.String(length=4), server_default='desc', nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('table_columns', sa.JSON(), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('font_family', sa.String(length=100), server_default='Georgia', nullable=False),
    sa.Column('font_size_px', sa.Integer(), server_default='16', nullable=False),
    sa.Column('line_spacing', sa.Float(), server_default='1.6', nullable=False),
    sa.Column('content_width_px', sa.Integer(), server_default='720', nullable=False),
    sa.Column('theme', sa.String(length=50), server_default='light', nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recent_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=1000), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ai_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_authors',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'author_id')
    )
    op.create_table('book_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=True),
    sa.Column('content_token_count', sa.Integer(), nullable=True),
    sa.Column('default_summary_id', sa.Integer(), nullable=True),
    sa.Column('section_type', sa.String(length=50), server_default='chapter', nullable=False),
    sa.Column('derived_from', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['default_summary_id'], ['summaries.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['parent_id'], ['book_sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book_sections', schema=None) as batch_op:
        batch_op.create_index('ix_book_sections_book_id_order', ['book_id', 'order_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_sections_section_type'), ['section_type'], unique=False)

    op.create_table('external_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('quality_notes', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_references', schema=None) as batch_op:
        batch_op.create_index('ix_external_references_book_id', ['book_id'], unique=False)

    op.create_table('processing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Enum('PARSE', 'SUMMARIZE', 'EMBED', 'EVAL', 'CAPTION', 'QUICK_SUMMARY', 'EXTERNAL_REFS', name='processingstep'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='processingjobstatus'), nullable=False),
    sa.Column('progress', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_processing_jobs_book_status', ['book_id', 'status'], unique=False)

    op.create_table('search_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('BOOK_TITLE', 'BOOK_SUMMARY', 'SECTION_TITLE', 'SECTION_CONTENT', 'SECTION_SUMMARY', 'CONCEPT', 'ANNOTATION', name='sourcetype'), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_index', schema=None) as batch_op:
        batch_op.create_index('ix_search_index_book_id', ['book_id'], unique=False)
        batch_op.create_index('ix_search_index_source', ['source_type', 'source_id'], unique=False)

    op.create_table('summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum('section', 'book', 'concept', 'annotation', name='summarycontenttype'), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('preset_name', sa.String(length=200), nullable=True),
    sa.Column('facets_used', sa.JSON(), nullable=False),
    sa.Column('prompt_text_sent', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('input_char_count', sa.Integer(), nullable=False),
    sa.Column('summary_char_count', sa.Integer(), nullable=False),
    sa.Column('summary_md', sa.Text(), nullable=False),
    sa.Column('eval_json', sa.JSON(), nullable=True),
    sa.Column('quality_warnings', sa.JSON(), nullable=True),
    sa.Column('retry_of_id', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retry_of_id'], ['summaries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.create_index('ix_summaries_book_id', ['book_id'], unique=False)
        batch_op.create_index('ix_summaries_content', ['content_type', 'content_id'], unique=False)
        batch_op.create_index('ix_summaries_created_at', ['created_at'], unique=False)

    op.create_table('taggables',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('taggable_type', sa.String(length=50), nullable=False),
    sa.Column('taggable_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'taggable_type', 'taggable_id')
    )
    op.create_table('ai_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['ai_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('first_section_id', sa.Integer(), nullable=True),
    sa.Column('term', sa.String(length=500), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('related_concepts', sa.JSON(), nullable=True),
    sa.Column('user_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['first_section_id'], ['book_sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'term', name='uq_concepts_book_term')
    )
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.create_index('ix_concepts_book_id', ['book_id'], unique=False)

    op.create_table('eval_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('summary_id', sa.Integer(), nullable=True),
    sa.Column('assertion_name', sa.String(length=100), nullable=False),
    sa.Column('assertion_category', sa.String(length=50), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('prompt_sent', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('llm_response', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('is_stale', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('eval_run_id', sa.String(length=36), nullable=True),
    sa.Column('likely_cause', sa.String(length=50), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['book_sections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['summary_id'], ['summaries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eval_traces', schema=None) as batch_op:
        batch_op.create_index('ix_eval_traces_assertion', ['assertion_name', 'passed'], unique=False)
        batch_op.create_index(batch_op.f('ix_eval_traces_eval_run_id'), ['eval_run_id'], unique=False)
        batch_op.create_index('ix_eval_traces_is_stale', ['is_stale'], unique=False, sqlite_where=sa.text('is_stale = 0'))
        batch_op.create_index('ix_eval_traces_section', ['section_id'], unique=False)

    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('caption_model', sa.String(length=100), nullable=True),
    sa.Column('relevance', sa.String(length=20), nullable=True),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['book_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('scroll_position', sa.Float(), nullable=True),
    sa.Column('content_mode', sa.String(length=20), server_default='summary', nullable=False),
    sa.Column('reading_preset_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reading_preset_id'], ['reading_presets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['book_sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_agent')
    )
    op.create_table('concept_sections',
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['book_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('concept_id', 'section_id')
    )
    # ### end Alembic commands ###

    # FTS5 virtual table for BM25 full-text search
    op.execute("""
        CREATE VIRTUAL TABLE IF NOT EXISTS search_fts USING fts5(
            chunk_text,
            content=search_index,
            content_rowid=id,
            tokenize='porter unicode61'
        )
    """)
    op.execute("""
        CREATE TRIGGER IF NOT EXISTS search_fts_ai AFTER INSERT ON search_index BEGIN
            INSERT INTO search_fts(rowid, chunk_text) VALUES (new.id, new.chunk_text);
        END
    """)
    op.execute("""
        CREATE TRIGGER IF NOT EXISTS search_fts_ad AFTER DELETE ON search_index BEGIN
            INSERT INTO search_fts(search_fts, rowid, chunk_text) VALUES ('delete', old.id, old.chunk_text);
        END
    """)
    op.execute("""
        CREATE TRIGGER IF NOT EXISTS search_fts_au AFTER UPDATE ON search_index BEGIN
            INSERT INTO search_fts(search_fts, rowid, chunk_text) VALUES ('delete', old.id, old.chunk_text);
            INSERT INTO search_fts(rowid, chunk_text) VALUES (new.id, new.chunk_text);
        END
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concept_sections')
    op.drop_table('reading_state')
    op.drop_table('images')
    with op.batch_alter_table('eval_traces', schema=None) as batch_op:
        batch_op.drop_index('ix_eval_traces_section')
        batch_op.drop_index('ix_eval_traces_is_stale', sqlite_where=sa.text('is_stale = 0'))
        batch_op.drop_index(batch_op.f('ix_eval_traces_eval_run_id'))
        batch_op.drop_index('ix_eval_traces_assertion')

    op.drop_table('eval_traces')
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.drop_index('ix_concepts_book_id')

    op.drop_table('concepts')
    op.drop_table('ai_messages')
    op.drop_table('taggables')
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.drop_index('ix_summaries_created_at')
        batch_op.drop_index('ix_summaries_content')
        batch_op.drop_index('ix_summaries_book_id')

    op.drop_table('summaries')
    with op.batch_alter_table('search_index', schema=None) as batch_op:
        batch_op.drop_index('ix_search_index_source')
        batch_op.drop_index('ix_search_index_book_id')

    op.drop_table('search_index')
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_processing_jobs_book_status')

    op.drop_table('processing_jobs')
    with op.batch_alter_table('external_references', schema=None) as batch_op:
        batch_op.drop_index('ix_external_references_book_id')

    op.drop_table('external_references')
    with op.batch_alter_table('book_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_sections_section_type'))
        batch_op.drop_index('ix_book_sections_book_id_order')

    op.drop_table('book_sections')
    op.drop_table('book_authors')
    op.drop_table('ai_threads')
    op.drop_table('tags')
    op.drop_table('recent_searches')
    op.drop_table('reading_presets')
    op.drop_table('library_views')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index('ix_books_status')
        batch_op.drop_index('ix_books_file_hash')

    op.drop_table('books')
    op.drop_table('authors')
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_index('ix_annotations_content')

    op.drop_table('annotations')
    # ### end Alembic commands ###
